Added graf component testing
vasylvovkglo/ui pull request #11
Opened 2022-01-11 08:57 UTC by vasylvovkglo

2022-01-12 10:04 UTC, dmytro-panchuk commented on tests/features/common/actions/common.action.js
> +    console.log(coordinates)
console.log

2022-01-12 10:04 UTC, dmytro-panchuk commented on tests/features/common/actions/graph.action.js
> +  console.log(array0, array1)
console.log

2022-01-12 10:04 UTC, dmytro-panchuk commented on tests/features/step-definitions/steps.js
> +  // checkNodesConnections,
unnecessary comment

2022-01-12 10:04 UTC, dmytro-panchuk commented on tests/features/common/actions/graph.action.js
> +// import { DataFrame } from 'pandas-js'
unnecessary comment

2022-01-12 10:04 UTC, dmytro-panchuk commented on tests/features/step-definitions/table.steps.js
> +  // getfieldAttributeValues
unnecessary comments

2022-01-12 10:04 UTC, dmytro-panchuk commented on tests/features/step-definitions/steps.js
> +    // await checkNodesConnections(this.driver, pageObjects[wizardName][graphName])
unnecessary comments

2022-01-14 08:48 UTC, illia-prokopchuk requested changes

2022-01-14 08:48 UTC, illia-prokopchuk commented on tests/features/common/actions/graph.action.js
> +  let diff = []
You can use Const

2022-01-14 08:48 UTC, illia-prokopchuk commented on tests/features/common/actions/graph.action.js
> +    let diffsMap = []
You can use Const

2022-01-14 08:48 UTC, illia-prokopchuk commented on tests/features/common/actions/graph.action.js
> +    console.log('\n', leftEdgesConnections)
remove console.log

2022-01-14 09:14 UTC, illia-prokopchuk requested changes

2022-01-14 09:14 UTC, illia-prokopchuk commented on tests/features/common/actions/graph.action.js
> +
remove empty line

2022-01-14 09:14 UTC, illia-prokopchuk commented on tests/features/common/actions/graph.action.js
> +    for (let i = 0; i < arrowsNodeRightEdgesX.length; i++) {
add empty line before "for"

2022-01-14 09:14 UTC, illia-prokopchuk commented on tests/features/common/actions/graph.action.js
> +    )
add empty line before "for"

2022-01-14 09:14 UTC, illia-prokopchuk commented on tests/features/common/actions/table.action.js
>      const rows = await getTableRows(driver, table)
add empty line after const

2022-01-14 09:14 UTC, illia-prokopchuk commented on tests/features/common/actions/table.action.js
>      let flag = true
move variable declaration to 59 row, and add empty line before "expect"

2022-01-14 09:14 UTC, illia-prokopchuk commented on tests/features/common/actions/table.action.js
>      const arr = []
add empty line

2022-01-14 09:14 UTC, illia-prokopchuk commented on tests/features/common/actions/table.action.js
>        const text = await getElementText(
move variable declaration to the top of loop, add empty line after variable declaration

2022-01-14 09:14 UTC, illia-prokopchuk commented on tests/features/common/actions/table.action.js
> +    const diff = differenceWith(arr, values, isEqual)
add empty line below

2022-01-14 09:14 UTC, illia-prokopchuk commented on tests/features/common/actions/table.action.js
> +      const position = await rowRoot.getRect()
add empty line below

2022-01-14 09:14 UTC, illia-prokopchuk commented on tests/features/common/actions/table.action.js
> +      const position = await rowRoot.getRect()
add empty line below

2022-01-14 09:14 UTC, illia-prokopchuk commented on tests/features/common/components/graph.component.js
> +  }
add empty line below

2022-01-14 09:14 UTC, illia-prokopchuk commented on tests/features/common/components/graph.component.js
> +  const grafConnections = {
Move variable declaration to the top of the function body

2022-01-14 09:14 UTC, illia-prokopchuk commented on tests/features/common/page-objects/info-pane.po.js
> +
delete empty line

2022-01-14 09:14 UTC, illia-prokopchuk commented on tests/features/common/page-objects/jobs-and-workflows.po.js
> +
delete empty line

2022-01-14 09:14 UTC, illia-prokopchuk commented on tests/features/step-definitions/steps.js
delete empty line

2022-01-14 12:18 UTC, merged